# Generated by Django 4.2 on 2023-04-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_remove_product_guarantee'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_username', models.CharField()),
                ('units_ordered', models.IntegerField(default=1)),
                ('Product', models.ManyToManyField(to='products.product')),
            ],
        ),
    ]
