# Generated by Django 4.2 on 2023-04-27 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_guarantee'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='orders',
            new_name='order',
        ),
    ]
