# Generated by Django 4.2 on 2023-04-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_orders_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='money',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
