# Generated by Django 4.2 on 2023-05-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vendor_username',
            field=models.CharField(blank=True),
        ),
    ]
