# Generated by Django 4.2 on 2023-05-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_photo_4_remove_product_photo_5_and_more'),
        ('orders', '0007_order_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField()),
                ('units', models.IntegerField(default=1)),
                ('Product_price', models.IntegerField()),
                ('Product', models.ManyToManyField(to='products.product')),
            ],
        ),
    ]
