# Generated by Django 4.2 on 2023-05-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_photo_4_remove_product_photo_5_and_more'),
        ('orders', '0008_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='customer',
            new_name='customer_username',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Product_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='units',
        ),
        migrations.CreateModel(
            name='cart_object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_username', models.CharField(blank=True)),
                ('units', models.IntegerField(blank=True)),
                ('price', models.IntegerField(blank=True)),
                ('Product', models.ManyToManyField(blank=True, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='item',
            field=models.ManyToManyField(to='orders.cart_object'),
        ),
    ]
