# Generated by Django 4.2 on 2023-05-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_photo_4_remove_product_photo_5_and_more'),
        ('orders', '0011_cart_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_username', models.CharField()),
                ('price', models.IntegerField(blank=True)),
                ('Product', models.ManyToManyField(blank=True, to='products.product')),
            ],
        ),
    ]
