# Generated by Django 4.2 on 2023-04-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('sport', models.CharField(max_length=100)),
                ('guarantee', models.IntegerField()),
                ('units_remaining', models.IntegerField()),
                ('dimensions', models.CharField(max_length=100)),
            ],
        ),
    ]
