# Generated by Django 4.2 on 2023-04-23 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_vendor'),
        ('products', '0003_product_photo_1_product_photo_2_product_photo_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.vendor'),
        ),
    ]
